server:
  servlet:
    context-path: /api
    session:
      persistent: false
  port: 7773

logging:
  level:
    com.musearllm.api: DEBUG
    org.mybatis: DEBUG
    org.springframework.data.redis: DEBUG

spring:
  application:
    name: MuseARLLMApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/art_museum_db
    username: postgres
    password: tkyungag55440023
    driver-class-name: org.postgresql.Driver
  # PostgreSQL 特定配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # 或者使用 none

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.musearllm.api.model
  type-handlers-package: com.musearllm.api.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-config: log4j2.xml

environment:
  domain: "127.0.0.1:7773"
